POST https://exp.host/--/api/v2/push/send HTTP/1.1
Content-Type: application/json

{
    "to": "ExponentPushToken[EwDPYnBTZ3-GgLZCedLIu1]",
    "title": "Lembrete do Dia",
    "body": "nada é tão ruim que não possa piorar"

}